# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See
# https://medium.com/staqu-dev-logs/keeping-python-code-clean-with-pre-commit-hooks-black-flake8-and-isort-cac8b01e0ea1
default_language_version:
  python: python3.9
exclude: (?x)(^docs/_build)
repos:
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black # Format Python code
    additional_dependencies: ["--index-url=https://pypi.org/simple/"]
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.4  # Use the sha / tag you want to point at
  hooks:
  - id: autopep8
    additional_dependencies: ["--index-url=https://pypi.org/simple/"]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8 # Apply flake 8 python file linter
    additional_dependencies:
    - "--index-url=https://pypi.org/simple/"
    - "flake8-annotations==2.5.0"
    - "flake8-bugbear==21.9.2"
    - "flake8-docstrings==1.5.0"
- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.1
  hooks:
  - id: yamllint # Check YAML Files
    args: ['-d', "{extends: relaxed, rules: {line-length: {max: 120 }}}"]
    additional_dependencies: ["--index-url=https://pypi.org/simple/"]
- repo: https://github.com/PyCQA/doc8
  rev: v1.0.0
  hooks:
  - id: doc8
    args: [--max-line-length, "120"]
    additional_dependencies: ["--index-url=https://pypi.org/simple/"]

