name: main-trigger-nameOfTheProject
on:
  workflow_dispatch:
  push:
    branches:
      - hossein-github-actions

env:
  test_cov: "Test coverage string."
jobs:
  main_trigger:
    name: 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9    
      - name: set outputs
        run: |
          echo "::set-output name=dev_version_tag::dev$(git rev-parse --short HEAD)"
      - name: Install requirements
        run: |
           pip3 install --require-hashes -r requirements.txt --no-deps --disable-pip-version-check
      - name: lint_repo
        uses: pre-commit/action@v3.0.0
      - name: Test_repo
        run: |
          pip install -e . --no-deps 
          pytest -n auto --cov=${{ env.test_cov }} --cov-config=.coveragerc --durations=0
      - name: Build_dist
        run: |
          python ./setup.py --version_tag ${{ steps.vars.outputs.dev_version_tag }} sdist bdist_wheel


