# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
    - cron: 21 18 * * *

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          days-before-stale: 30
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: This is issue is marked as stale as it has been inactive for 30 days. It will closed in 7 days.
          stale-pr-message: This is PR is marked as stale as it has been inactive for 30 days. It will closed in 7 days.
          stale-issue-label: no-issue-activity
          stale-pr-label: no-pr-activity
